services:
  backend:
    build: ./supchat-backend-main
    ports:
      - "5000:5000"
    env_file:
      - env.txt
  frontend:
    build: ./supchat-web-main
    ports:
      - "3000:80"
    depends_on:
      - backend

